# Generated by Django 5.1.1 on 2024-10-01 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('post', models.ImageField(upload_to='event_post/')),
                ('location', models.TextField()),
                ('event_time', models.TimeField()),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('campus_name', models.CharField(max_length=250)),
                ('faculty', models.CharField(choices=[('BEI', 'Electronics, Communication, and Information Engineering'), ('BCT', 'Computer Engineering'), ('BCE', 'Civil Engineering'), ('BEE', 'Electrical Engineering'), ('BME', 'Mechanical Engineering'), ('BAR', 'Architecture'), ('BAE', 'Automobile Engineering'), ('BIE', 'Industrial Engineering'), ('BGE', 'Geomatics Engineering'), ('BAGE', 'Agricultural Engineering'), ('BCHE', 'Chemical Engineering')], default='BEI', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventmodel')),
                ('participant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_link', models.TextField()),
                ('certificate_sent', models.BooleanField(default=False)),
                ('certificate_sent_on', models.DateTimeField(blank=True, null=True)),
                ('event_reg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.eventreg')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
                ('certificate_url', models.CharField(max_length=300)),
                ('cert_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.participants')),
            ],
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userdata'),
        ),
    ]
