# Generated by Django 5.1.1 on 2024-10-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdata_groups_userdata_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
