# Generated by Django 5.1.1 on 2024-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userdata_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreg',
            name='event_id',
        ),
        migrations.AddField(
            model_name='eventreg',
            name='event_id',
            field=models.ManyToManyField(to='api.eventmodel'),
        ),
    ]
